name: employee_tracker
description: "Offline-Ready Employee Tracking App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management & DI
  get: ^4.6.6

  # Networking & Connectivity
  dio: ^5.4.3+1
  connectivity_plus: ^6.0.3

  # Offline Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Background Service & Location
  flutter_background_service: ^5.0.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  permission_handler: ^11.3.0
  google_maps_flutter: ^2.5.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.9